# Configuration for github/issue-labeler - body-based labels
# See: https://github.com/github/issue-labeler
# Uses regex patterns to match PR/issue body content
# Checkbox patterns use (.|[\r\n])*? for cross-line matching ([\s\S] may not work in all engines)
---
bug:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Bb]ugfix'

enhancement:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Nn]ew [Ff]eature'

breaking-change:
  # Simple checkbox pattern - matches checked Breaking change checkbox
  - '- \[x\] Breaking change'
  - '- \[X\] Breaking change'
  # Breaking change section header followed by content
  - '# Breaking change\n\n[A-Z]'

code-quality:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Cc]ode [Qq]uality'
