# Configuration for github/issue-labeler - body-based labels
# See: https://github.com/github/issue-labeler
# Uses regex patterns to match PR/issue body content
#
# IMPORTANT: Multiple patterns in an array use AND logic (all must match).
# Use regex alternation (|) within a single pattern for OR logic.
# Patterns use (.|[\r\n])*? for cross-line matching ([\s\S] may not work in all engines)
---
bug:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Bb]ugfix'

enhancement:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Nn]ew [Ff]eature'

breaking-change:
  # OR logic: checkbox checked OR section has content
  # Pattern 1: Checked checkbox after "Type of change" header
  # Pattern 2: "# Breaking change" section with actual content (skips HTML template comment)
  # yamllint disable-line rule:line-length
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Bb]reaking [Cc]hange|# [Bb]reaking [Cc]hange\s*(<!--(.|[\r\n])*?-->\s*)?[A-Z]'

code-quality:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Cc]ode [Qq]uality'
