# Configuration for github/issue-labeler - body-based labels
# See: https://github.com/github/issue-labeler
# Uses regex patterns to match PR/issue body content
# Note: [xX] matches both lowercase and uppercase X in checkboxes
---
bug:
  - '\[[xX]\]\s*[Bb]ugfix'

enhancement:
  - '\[[xX]\]\s*[Nn]ew [Ff]eature'

breaking-change:
  # Checkbox pattern - requires "- " prefix to avoid matching inline code examples
  - '- \[[xX]\]\s*[Bb]reaking [Cc]hange'
  # Match breaking change section with content after HTML comment.
  # Uses ^[\s\S]*? to find FIRST # Breaking change, requires ## Proposed change AFTER.
  # This ignores any # Breaking change in code blocks after ## Proposed change.
  - '^[\s\S]*?# Breaking change[\s\S]*?-->\s*\n+[A-Z][a-z]+[\s\S]*?## Proposed change'
  # Match when HTML comment is removed and content added directly
  - '^[\s\S]*?# Breaking change\s*\n+[A-Z][a-z]+[\s\S]*?## Proposed change'

code-quality:
  - '\[[xX]\]\s*[Cc]ode [Qq]uality'
