# Configuration for github/issue-labeler - body-based labels
# See: https://github.com/github/issue-labeler
# Uses regex patterns to match PR/issue body content
# Checkbox patterns use (.|[\r\n])*? for cross-line matching ([\s\S] may not work in all engines)
---
bug:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Bb]ugfix'

enhancement:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Nn]ew [Ff]eature'

breaking-change:
  # Checkbox in Type of change section
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Bb]reaking [Cc]hange'
  # Breaking change section with content after HTML comment
  - '# Breaking change(.|[\r\n])*?-->\s*\n+[A-Z][a-z]+(.|[\r\n])*?## Proposed change'
  # Breaking change section with HTML comment removed
  - '# Breaking change\s*\n+[A-Z][a-z]+(.|[\r\n])*?## Proposed change'

code-quality:
  - '## Type of change(.|[\r\n])*?- \[[xX]\]\s*[Cc]ode [Qq]uality'
