---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
autolabeler:
  - label: 'javascript'
    files:
      - '*.ts'
      - '*.js'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.eslintrc.cjs'
      - 'tsconfig.json'
      - 'rollup.config.js'
  - label: 'python'
    files:
      - 'requirements_*.txt'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'setup.py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '*.py'
  - label: 'github_actions'
    files:
      - '.github/*'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancements :zap:"
    labels:
      - "enhancement"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: ":mortar_board: Code Quality :mortar_board:"
    labels:
      - "code-quality"
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
# yamllint disable rule:line-length
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/raman325/lock_code_manager/$RESOLVED_VERSION/total.svg)](https://github.com/raman325/lock_code_manager/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Wiki](https://github.com/raman325/lock_code_manager/wiki)
  - [Submit bugs/feature requests](https://github.com/raman325/lock_code_manager/issues)
