---
name: Feature request
description: Suggest an idea for this project
title: "[Feature Request] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: If applicable, please describe the problem you are trying to solve with this request
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Please describe the feature request with as much detail as you can
    validations:
      required: true
  - type: textarea
    id: else
    attributes:
      label: Anything else?
      description: Is there any other information that's worth mentioning?
