#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

if [ ! -n "$DEVCONTAINER" ] && [ ! -n "$VIRTUAL_ENV" ];then
  python3.13 -m venv venv
  source venv/bin/activate
fi

python -m pip install -r requirements_dev.txt

pre-commit install

yarn install
