---
hard_refresh_usercodes:
  target:
    entity:
      domain: lock

set_usercode:
  fields:
    lock_entity_id:
      required: true
      selector:
        entity:
          domain: lock
    code_slot:
      required: true
      selector:
        number:
          min: 1
          mode: box
    usercode:
      required: true
      selector:
        text:

clear_usercode:
  fields:
    lock_entity_id:
      required: true
      selector:
        entity:
          domain: lock
    code_slot:
      required: true
      selector:
        number:
          min: 1
          mode: box

set_slot_condition:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: lock_code_manager
    config_entry_title:
      selector:
        text:
    slot:
      required: true
      selector:
        number:
          min: 1
          max: 9999
          mode: box
    entity_id:
      required: true
      selector:
        entity:
          domain:
            - binary_sensor
            - calendar
            - input_boolean
            - schedule
            - switch

clear_slot_condition:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: lock_code_manager
    config_entry_title:
      selector:
        text:
    slot:
      required: true
      selector:
        number:
          min: 1
          max: 9999
          mode: box

add_user:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: lock_code_manager
    config_entry_title:
      selector:
        text:
    name:
      required: true
      selector:
        text:
    pin:
      selector:
        text:
    enabled:
      default: true
      selector:
        boolean:
    condition:
      selector:
        entity:
          domain:
            - binary_sensor
            - calendar
            - input_boolean
            - schedule
            - switch

delete_user:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: lock_code_manager
    config_entry_title:
      selector:
        text:
    name:
      required: true
      selector:
        text:
    clear_credentials:
      default: true
      selector:
        boolean:

generate_pin:
  fields:
    length:
      default: 4
      example: 4
      selector:
        number:
          min: 4
          max: 12
          step: 1
          mode: box

deobfuscate_log:
  fields:
    text:
      required: true
      selector:
        text:
          multiline: true
