hard_refresh_usercodes:
  name: Hard Refresh Usercodes
  description: If Lock Code Manager supports the lock's integration, and the lock's integration supports it, this will query the lock for all usercodes. This is potentially useful for integrations that cache data from the lock and a usercode(s) is configured outside of Home Assistant.
  target:
    entity:
      domain: lock
